# Generated by Django 4.1.7 on 2023-03-18 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('s', 'статья'), ('n', 'новость')], max_length=255)),
                ('data_create', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('connection_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.author')),
                ('connection_category', models.ManyToManyField(to='news.category')),
            ],
        ),
    ]
