# Generated by Django 4.1.7 on 2023-03-18 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.category')),
                ('connection_post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='news.post')),
            ],
        ),
    ]
