# Generated by Django 4.1.7 on 2023-03-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_author_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='connection_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='rating',
            new_name='comment_rating',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='connection_post',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='connection_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='connection_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='connection_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='rating',
            new_name='post_rating',
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='connection_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='connection_post',
            new_name='post',
        ),
        migrations.RemoveField(
            model_name='author',
            name='rating',
        ),
        migrations.AddField(
            model_name='author',
            name='author_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('article', 'статья'), ('news', 'новость')], max_length=255),
        ),
    ]
