# Generated by Django 4.1.7 on 2023-03-23 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_rename_connection_user_author_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='user',
            new_name='user1',
        ),
    ]
