# Generated by Django 4.1.7 on 2023-03-23 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_rename_user_author_user1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='user1',
            new_name='user',
        ),
    ]
