# Generated by Django 4.1.7 on 2023-03-23 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_rename_user1_author_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='type',
        ),
        migrations.AddField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('SP', 'Спорт'), ('PO', 'Политика'), ('ED', 'Образование'), ('WE', 'Погода')], default='SP', max_length=2, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='types',
            field=models.CharField(choices=[('ARTI', 'Статья'), ('NEWS', 'Новость')], default='NEWS', max_length=4),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(through='news.PostCategory', to='news.category'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.post'),
        ),
    ]
